version: "3.9"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/pennypal-backend:latest
    container_name: pennypal-backend
    ports:
      - "8080:8080"
    env_file:
      - pennypal.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    image: ${DOCKERHUB_USERNAME}/pennypal-frontend:latest
    container_name: pennypal-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: pennypal-db
    environment:
      POSTGRES_DB: pennypal
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7
    container_name: pennypal-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
